FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine-slim
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /app
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
